export const ARTICLE_LIST = 'home/ARTICLE_LIST';
export const ARTICLE_LIST_SUCCESS = 'home/ARTICLE_LIST_SUCCESS';
export const SWIPER_LIST = 'home/SWIPER_LIST';
export const SWIPER_LIST_SUCCESS = 'home/SWIPER_LIST_SUCCESS';
export const ARTICLE_RAND_COMMENT_LIST = 'home/ARTICLE_RAND_COMMENT_LIST';
export const ARTICLE_RAND_COMMENT_LIST_SUCCESS = 'home/ARTICLE_RAND_COMMENT_LIST_SUCCESS';
export const SET_MESSAGE = 'home/SET_MESSAGE';