export const ARTICLE_RAND_COMMENT_LIST = 'sidebar/ARTICLE_RAND_COMMENT_LIST';
export const ARTICLE_RAND_COMMENT_LIST_SUCCESS = 'sidebar/ARTICLE_RAND_COMMENT_LIST_SUCCESS';
export const SET_MESSAGE = 'sidebar/SET_MESSAGE';